name: biosys-hydrogrow

services:
  flutter-web:
    image: ghcr.io/cirruslabs/flutter:3.41.1
    working_dir: /workspace
    volumes:
      - ./archive:/workspace
      - flutter-pub-cache:/root/.pub-cache
      - flutter-gradle-cache:/root/.gradle
    ports:
      - "8080:8080"
    environment:
      - CI=true
    command: >
      bash -lc
      "flutter pub get &&
       flutter run -d web-server --web-hostname=0.0.0.0 --web-port=8080"

  flutter-apk:
    image: ghcr.io/cirruslabs/flutter:3.41.1
    working_dir: /workspace
    volumes:
      - ./archive:/workspace
      - ./dist:/dist
      - flutter-pub-cache:/root/.pub-cache
      - flutter-gradle-cache:/root/.gradle
    environment:
      - CI=true
    command: >
      bash -lc
      "flutter pub get &&
       flutter build apk --release &&
       cp build/app/outputs/flutter-apk/app-release.apk /dist/HydroGrow.apk"

volumes:
  flutter-pub-cache:
  flutter-gradle-cache:
