// Generated by `flutterfire configure` (FlutterFire CLI).
//
// This placeholder exists so the app compiles before Firebase is configured.
// Run:
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=biosense-3bd53
// ...then replace this file with the generated output.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyCOkkpK-cggYsfc9xm3orWoCv44JQGDgM0",
  authDomain: "biosense-3bd53.firebaseapp.com",
  databaseURL: "https://biosense-3bd53-default-rtdb.firebaseio.com",
  projectId: "biosense-3bd53",
  storageBucket: "biosense-3bd53.firebasestorage.app",
  messagingSenderId: "997859569821",
  appId: "1:997859569821:web:a62699b6d9c370eb086474",
  measurementId: "G-EFYY0M7MMW"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARGuSr4OvR0tG5AioNqwFtalw_jVcybmQ',
    appId: '1:997859569821:android:528d185bbb1ae0a1086474',
    messagingSenderId: '997859569821',
    projectId: 'biosense-3bd53',
    storageBucket: 'biosense-3bd53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwcTjfeIrY3BQ3Vc1QlAN5mwA9c2U44hY',
    appId: '1:997859569821:ios:5ade888a5c0aef98086474',
    messagingSenderId: '997859569821',
    projectId: 'biosense-3bd53',
    storageBucket: 'biosense-3bd53.firebasestorage.app',
    iosBundleId: 'com.example.hydrosenseCompanionApp549065841',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwcTjfeIrY3BQ3Vc1QlAN5mwA9c2U44hY',
    appId: '1:997859569821:ios:5ade888a5c0aef98086474',
    messagingSenderId: '997859569821',
    projectId: 'biosense-3bd53',
    storageBucket: 'biosense-3bd53.firebasestorage.app',
    iosBundleId: 'com.example.hydrosenseCompanionApp549065841',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOkkpK-cggYsfc9xm3orWoCv44JQGDgM0',
    appId: '1:997859569821:web:9cd2b23e17f34376086474',
    messagingSenderId: '997859569821',
    projectId: 'biosense-3bd53',
    authDomain: 'biosense-3bd53.firebaseapp.com',
    storageBucket: 'biosense-3bd53.firebasestorage.app',
    measurementId: 'G-GXZNFD1D9G',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'biosense-3bd53',
  );
}
